<?php

function private_messages_form_privatemsg_new_alter(&$form, &$form_state){
	if(isset($_GET['user']) && $_GET['user'] != ""){
		$form['recipient']['#value'] = $_GET['user'];
	}else{
		$title = t("Type your message here");
		global $user;
		if(arg(0) == 'user' && $user->uid != 0){
			$user_ = user_load(arg(1));
			$form['recipient']['#value'] = $user_->name;
			if($user->uid != 0){
				$form['subject']['#value'] = "From ".$user->name;
			}
			$form['body']['#title'] = $title;	
		}elseif(arg(0) == 'node' && $user->uid != 0){
			$node = node_load(arg(1));
			$user_ = user_load($node->uid);
			$form['recipient']['#value'] = $user_->name;
			if($node->uid != 0){
				$form['subject']['#value'] = "From ".$user->name;
			}
			$form['body']['#title'] = $title;			
		}
	}
	//$form['#after_build'][] = 'private_messages_form_after_build';
 /*$form['body']['#type'] = 'textarea';
 $form['signature_settings']['signature']['#type'] = 'plain_text';*/
}


?>
