<?php
function panels_hooks_panels_pane_content_alter($content, $pane, $args, $contexts) {
	$panel_array = Array();
	$panel_array = $pane->configuration;
	if(array_key_exists("admin_title", $panel_array)){
		foreach($contexts as $context){
			$data = $context->data;
		}		
		if($panel_array["admin_title"] == "Listing"){
			$query = new EntityFieldQuery();
			$query->entityCondition('entity_type', 'node')
				->entityCondition('bundle', 'property')
				->propertyCondition('status', NODE_PUBLISHED)
			;
			$result = $query->execute();
			$count = count($result['node']);			
			
			$query = new EntityFieldQuery();
			$query->entityCondition('entity_type', 'node')
				->entityCondition('bundle', 'accomodation')
				->propertyCondition('status', NODE_PUBLISHED)
			;
			$result = $query->execute();
			$count_accomodation = count($result['node']);
			
			$output = "<div class='tenants front_page_module' id='front_page_module'>";
			$output .= "</div>";
			$output .= "<input type='hidden' id='all-property' value='" . $count . "'>";
			$output .= "<input type='hidden' id='all-accomodation' value='" . $count_accomodation . "'>";
			$content->content = $output;
		}elseif($panel_array["admin_title"] == "Verified"){
			$em = t("Email");
			$ph = t("Phone");
			$content->content = "<div class='email col-md-6 col-sm-6 col-xs-12'>".$em."</div>";
			$content->content .= "<div class='phone col-md-6 col-sm-6 col-xs-12'>".$ph."</div>";
		}elseif($panel_array["admin_title"] == "Is Online"){
			$user_ = user_load(arg(1));
			$logged = "";
			if(user_is_logged_in($user_ -> uid)){
				$online = t("Online Today");
				$logged = "<div class='is-logged'>" . $online . "</div>";
			}
			foreach($user_ -> roles as $key=>$role){
				if($key > 2){
					$role_class = strtolower($role);
					$status = "<div class='role " . $role_class . "'>" . $role . "</div>";
				}elseif($key == 2){
					$role = t("Authentic");
					$role_class = strtolower($role);					
					$status = "<div class='role " . $role_class . "'>" . $role . "</div>";
				}
			}		
			$content->content = $logged.$status;
		}
		if($panel_array["admin_title"] == "Search Listing"){
			$query = new EntityFieldQuery();
			$query->entityCondition('entity_type', 'node')
				->entityCondition('bundle', 'property')
				->propertyCondition('status', NODE_PUBLISHED)
			;
			$result = $query->execute();
			$count = count($result['node']);
			
			$query = new EntityFieldQuery();
			$query->entityCondition('entity_type', 'node')
				->entityCondition('bundle', 'accomodation')
				->propertyCondition('status', NODE_PUBLISHED)
			;
			$result = $query->execute();
			$count_accomodation = count($result['node']);
			
			$output = "<div class='search_form'>";
			$tx = t('Show search form');
			//$output .= '<a class="colorbox-node search_form" href="/search_form_rooms" data-href="/search_form_rooms?width=600&height=600">' . $tx . '</a>';
			$output .= '<div class="link"><a class="search_form" href="/search_form_rooms" data-href="/search_form_rooms?width=600&height=600">' . $tx . '</a></div>';
			$output .= "</div>";
			$output .= "<div class='tenants front_page_module' id='search_module'>";
			$output .= "</div>";
			$output .= "<input type='hidden' id='all-property' value='" . $count . "'>";
			$output .= "<input type='hidden' id='all-accomodation' value='" . $count_accomodation . "'>";
			$content->content = $output;			
		}
	}
}
